# Generated by Django 4.2.4 on 2023-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csfdScraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AlterField(
            model_name='actor',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
