# Generated by Django 4.2.4 on 2023-09-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csfdScraper', '0002_remove_movie_actors_alter_actor_normalized_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csfdScraper.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csfdScraper.movie')),
            ],
        ),
    ]
